// Code generated by ent, DO NOT EDIT.

package member

import (
	"radgifa/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldID, id))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldDisplayName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldCreatedAt, v))
}

// UniqueIdentifier applies equality check predicate on the "unique_identifier" field. It's identical to UniqueIdentifierEQ.
func UniqueIdentifier(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldUniqueIdentifier, v))
}

// PassCode applies equality check predicate on the "pass_code" field. It's identical to PassCodeEQ.
func PassCode(v []byte) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldPassCode, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldDisplayName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldCreatedAt, v))
}

// UniqueIdentifierEQ applies the EQ predicate on the "unique_identifier" field.
func UniqueIdentifierEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldUniqueIdentifier, v))
}

// UniqueIdentifierNEQ applies the NEQ predicate on the "unique_identifier" field.
func UniqueIdentifierNEQ(v string) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldUniqueIdentifier, v))
}

// UniqueIdentifierIn applies the In predicate on the "unique_identifier" field.
func UniqueIdentifierIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldUniqueIdentifier, vs...))
}

// UniqueIdentifierNotIn applies the NotIn predicate on the "unique_identifier" field.
func UniqueIdentifierNotIn(vs ...string) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldUniqueIdentifier, vs...))
}

// UniqueIdentifierGT applies the GT predicate on the "unique_identifier" field.
func UniqueIdentifierGT(v string) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldUniqueIdentifier, v))
}

// UniqueIdentifierGTE applies the GTE predicate on the "unique_identifier" field.
func UniqueIdentifierGTE(v string) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldUniqueIdentifier, v))
}

// UniqueIdentifierLT applies the LT predicate on the "unique_identifier" field.
func UniqueIdentifierLT(v string) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldUniqueIdentifier, v))
}

// UniqueIdentifierLTE applies the LTE predicate on the "unique_identifier" field.
func UniqueIdentifierLTE(v string) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldUniqueIdentifier, v))
}

// UniqueIdentifierContains applies the Contains predicate on the "unique_identifier" field.
func UniqueIdentifierContains(v string) predicate.Member {
	return predicate.Member(sql.FieldContains(FieldUniqueIdentifier, v))
}

// UniqueIdentifierHasPrefix applies the HasPrefix predicate on the "unique_identifier" field.
func UniqueIdentifierHasPrefix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasPrefix(FieldUniqueIdentifier, v))
}

// UniqueIdentifierHasSuffix applies the HasSuffix predicate on the "unique_identifier" field.
func UniqueIdentifierHasSuffix(v string) predicate.Member {
	return predicate.Member(sql.FieldHasSuffix(FieldUniqueIdentifier, v))
}

// UniqueIdentifierEqualFold applies the EqualFold predicate on the "unique_identifier" field.
func UniqueIdentifierEqualFold(v string) predicate.Member {
	return predicate.Member(sql.FieldEqualFold(FieldUniqueIdentifier, v))
}

// UniqueIdentifierContainsFold applies the ContainsFold predicate on the "unique_identifier" field.
func UniqueIdentifierContainsFold(v string) predicate.Member {
	return predicate.Member(sql.FieldContainsFold(FieldUniqueIdentifier, v))
}

// PassCodeEQ applies the EQ predicate on the "pass_code" field.
func PassCodeEQ(v []byte) predicate.Member {
	return predicate.Member(sql.FieldEQ(FieldPassCode, v))
}

// PassCodeNEQ applies the NEQ predicate on the "pass_code" field.
func PassCodeNEQ(v []byte) predicate.Member {
	return predicate.Member(sql.FieldNEQ(FieldPassCode, v))
}

// PassCodeIn applies the In predicate on the "pass_code" field.
func PassCodeIn(vs ...[]byte) predicate.Member {
	return predicate.Member(sql.FieldIn(FieldPassCode, vs...))
}

// PassCodeNotIn applies the NotIn predicate on the "pass_code" field.
func PassCodeNotIn(vs ...[]byte) predicate.Member {
	return predicate.Member(sql.FieldNotIn(FieldPassCode, vs...))
}

// PassCodeGT applies the GT predicate on the "pass_code" field.
func PassCodeGT(v []byte) predicate.Member {
	return predicate.Member(sql.FieldGT(FieldPassCode, v))
}

// PassCodeGTE applies the GTE predicate on the "pass_code" field.
func PassCodeGTE(v []byte) predicate.Member {
	return predicate.Member(sql.FieldGTE(FieldPassCode, v))
}

// PassCodeLT applies the LT predicate on the "pass_code" field.
func PassCodeLT(v []byte) predicate.Member {
	return predicate.Member(sql.FieldLT(FieldPassCode, v))
}

// PassCodeLTE applies the LTE predicate on the "pass_code" field.
func PassCodeLTE(v []byte) predicate.Member {
	return predicate.Member(sql.FieldLTE(FieldPassCode, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQuestionnaire applies the HasEdge predicate on the "questionnaire" edge.
func HasQuestionnaire() predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuestionnaireTable, QuestionnaireColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestionnaireWith applies the HasEdge predicate on the "questionnaire" edge with a given conditions (other predicates).
func HasQuestionnaireWith(preds ...predicate.Questionnaire) predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := newQuestionnaireStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnswers applies the HasEdge predicate on the "answers" edge.
func HasAnswers() predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AnswersTable, AnswersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnswersWith applies the HasEdge predicate on the "answers" edge with a given conditions (other predicates).
func HasAnswersWith(preds ...predicate.Answer) predicate.Member {
	return predicate.Member(func(s *sql.Selector) {
		step := newAnswersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Member) predicate.Member {
	return predicate.Member(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Member) predicate.Member {
	return predicate.Member(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Member) predicate.Member {
	return predicate.Member(sql.NotPredicates(p))
}
