// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnswersColumns holds the columns for the "answers" table.
	AnswersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "answer_value", Type: field.TypeEnum, Enums: []string{"Yes", "No", "Pass"}},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "member_answers", Type: field.TypeUUID},
		{Name: "question_answers", Type: field.TypeUUID},
	}
	// AnswersTable holds the schema information for the "answers" table.
	AnswersTable = &schema.Table{
		Name:       "answers",
		Columns:    AnswersColumns,
		PrimaryKey: []*schema.Column{AnswersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "answers_members_answers",
				Columns:    []*schema.Column{AnswersColumns[4]},
				RefColumns: []*schema.Column{MembersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "answers_questions_answers",
				Columns:    []*schema.Column{AnswersColumns[5]},
				RefColumns: []*schema.Column{QuestionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// MembersColumns holds the columns for the "members" table.
	MembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "display_name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "unique_identifier", Type: field.TypeString},
		{Name: "pass_code", Type: field.TypeBytes},
		{Name: "questionnaire_members", Type: field.TypeUUID},
		{Name: "user_memberships", Type: field.TypeUUID, Nullable: true},
	}
	// MembersTable holds the schema information for the "members" table.
	MembersTable = &schema.Table{
		Name:       "members",
		Columns:    MembersColumns,
		PrimaryKey: []*schema.Column{MembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "members_questionnaires_members",
				Columns:    []*schema.Column{MembersColumns[5]},
				RefColumns: []*schema.Column{QuestionnairesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "members_users_memberships",
				Columns:    []*schema.Column{MembersColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "member_unique_identifier_questionnaire_members",
				Unique:  true,
				Columns: []*schema.Column{MembersColumns[3], MembersColumns[5]},
			},
		},
	}
	// QuestionsColumns holds the columns for the "questions" table.
	QuestionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "theme", Type: field.TypeString, Size: 255},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "text", Type: field.TypeString},
		{Name: "questionnaire_questions", Type: field.TypeUUID},
	}
	// QuestionsTable holds the schema information for the "questions" table.
	QuestionsTable = &schema.Table{
		Name:       "questions",
		Columns:    QuestionsColumns,
		PrimaryKey: []*schema.Column{QuestionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "questions_questionnaires_questions",
				Columns:    []*schema.Column{QuestionsColumns[4]},
				RefColumns: []*schema.Column{QuestionnairesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// QuestionnairesColumns holds the columns for the "questionnaires" table.
	QuestionnairesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "user_questionnaires", Type: field.TypeUUID},
	}
	// QuestionnairesTable holds the schema information for the "questionnaires" table.
	QuestionnairesTable = &schema.Table{
		Name:       "questionnaires",
		Columns:    QuestionnairesColumns,
		PrimaryKey: []*schema.Column{QuestionnairesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "questionnaires_users_questionnaires",
				Columns:    []*schema.Column{QuestionnairesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "password", Type: field.TypeBytes},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnswersTable,
		MembersTable,
		QuestionsTable,
		QuestionnairesTable,
		UsersTable,
	}
)

func init() {
	AnswersTable.ForeignKeys[0].RefTable = MembersTable
	AnswersTable.ForeignKeys[1].RefTable = QuestionsTable
	MembersTable.ForeignKeys[0].RefTable = QuestionnairesTable
	MembersTable.ForeignKeys[1].RefTable = UsersTable
	QuestionsTable.ForeignKeys[0].RefTable = QuestionnairesTable
	QuestionnairesTable.ForeignKeys[0].RefTable = UsersTable
}
