// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"radgifa/ent/answer"
	"radgifa/ent/member"
	"radgifa/ent/predicate"
	"radgifa/ent/question"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AnswerUpdate is the builder for updating Answer entities.
type AnswerUpdate struct {
	config
	hooks    []Hook
	mutation *AnswerMutation
}

// Where appends a list predicates to the AnswerUpdate builder.
func (_u *AnswerUpdate) Where(ps ...predicate.Answer) *AnswerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAnswerValue sets the "answer_value" field.
func (_u *AnswerUpdate) SetAnswerValue(v answer.AnswerValue) *AnswerUpdate {
	_u.mutation.SetAnswerValue(v)
	return _u
}

// SetNillableAnswerValue sets the "answer_value" field if the given value is not nil.
func (_u *AnswerUpdate) SetNillableAnswerValue(v *answer.AnswerValue) *AnswerUpdate {
	if v != nil {
		_u.SetAnswerValue(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnswerUpdate) SetUpdatedAt(v int64) *AnswerUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AnswerUpdate) SetNillableUpdatedAt(v *int64) *AnswerUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *AnswerUpdate) AddUpdatedAt(v int64) *AnswerUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_u *AnswerUpdate) SetQuestionID(id uuid.UUID) *AnswerUpdate {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetQuestion sets the "question" edge to the Question entity.
func (_u *AnswerUpdate) SetQuestion(v *Question) *AnswerUpdate {
	return _u.SetQuestionID(v.ID)
}

// SetMemberID sets the "member" edge to the Member entity by ID.
func (_u *AnswerUpdate) SetMemberID(id uuid.UUID) *AnswerUpdate {
	_u.mutation.SetMemberID(id)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *AnswerUpdate) SetMember(v *Member) *AnswerUpdate {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the AnswerMutation object of the builder.
func (_u *AnswerUpdate) Mutation() *AnswerMutation {
	return _u.mutation
}

// ClearQuestion clears the "question" edge to the Question entity.
func (_u *AnswerUpdate) ClearQuestion() *AnswerUpdate {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *AnswerUpdate) ClearMember() *AnswerUpdate {
	_u.mutation.ClearMember()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnswerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnswerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnswerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnswerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnswerUpdate) check() error {
	if v, ok := _u.mutation.AnswerValue(); ok {
		if err := answer.AnswerValueValidator(v); err != nil {
			return &ValidationError{Name: "answer_value", err: fmt.Errorf(`ent: validator failed for field "Answer.answer_value": %w`, err)}
		}
	}
	if _u.mutation.QuestionCleared() && len(_u.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Answer.question"`)
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Answer.member"`)
	}
	return nil
}

func (_u *AnswerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(answer.Table, answer.Columns, sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AnswerValue(); ok {
		_spec.SetField(answer.FieldAnswerValue, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(answer.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(answer.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.MemberTable,
			Columns: []string{answer.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.MemberTable,
			Columns: []string{answer.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnswerUpdateOne is the builder for updating a single Answer entity.
type AnswerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnswerMutation
}

// SetAnswerValue sets the "answer_value" field.
func (_u *AnswerUpdateOne) SetAnswerValue(v answer.AnswerValue) *AnswerUpdateOne {
	_u.mutation.SetAnswerValue(v)
	return _u
}

// SetNillableAnswerValue sets the "answer_value" field if the given value is not nil.
func (_u *AnswerUpdateOne) SetNillableAnswerValue(v *answer.AnswerValue) *AnswerUpdateOne {
	if v != nil {
		_u.SetAnswerValue(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnswerUpdateOne) SetUpdatedAt(v int64) *AnswerUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AnswerUpdateOne) SetNillableUpdatedAt(v *int64) *AnswerUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *AnswerUpdateOne) AddUpdatedAt(v int64) *AnswerUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// SetQuestionID sets the "question" edge to the Question entity by ID.
func (_u *AnswerUpdateOne) SetQuestionID(id uuid.UUID) *AnswerUpdateOne {
	_u.mutation.SetQuestionID(id)
	return _u
}

// SetQuestion sets the "question" edge to the Question entity.
func (_u *AnswerUpdateOne) SetQuestion(v *Question) *AnswerUpdateOne {
	return _u.SetQuestionID(v.ID)
}

// SetMemberID sets the "member" edge to the Member entity by ID.
func (_u *AnswerUpdateOne) SetMemberID(id uuid.UUID) *AnswerUpdateOne {
	_u.mutation.SetMemberID(id)
	return _u
}

// SetMember sets the "member" edge to the Member entity.
func (_u *AnswerUpdateOne) SetMember(v *Member) *AnswerUpdateOne {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the AnswerMutation object of the builder.
func (_u *AnswerUpdateOne) Mutation() *AnswerMutation {
	return _u.mutation
}

// ClearQuestion clears the "question" edge to the Question entity.
func (_u *AnswerUpdateOne) ClearQuestion() *AnswerUpdateOne {
	_u.mutation.ClearQuestion()
	return _u
}

// ClearMember clears the "member" edge to the Member entity.
func (_u *AnswerUpdateOne) ClearMember() *AnswerUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// Where appends a list predicates to the AnswerUpdate builder.
func (_u *AnswerUpdateOne) Where(ps ...predicate.Answer) *AnswerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnswerUpdateOne) Select(field string, fields ...string) *AnswerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Answer entity.
func (_u *AnswerUpdateOne) Save(ctx context.Context) (*Answer, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnswerUpdateOne) SaveX(ctx context.Context) *Answer {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnswerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnswerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnswerUpdateOne) check() error {
	if v, ok := _u.mutation.AnswerValue(); ok {
		if err := answer.AnswerValueValidator(v); err != nil {
			return &ValidationError{Name: "answer_value", err: fmt.Errorf(`ent: validator failed for field "Answer.answer_value": %w`, err)}
		}
	}
	if _u.mutation.QuestionCleared() && len(_u.mutation.QuestionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Answer.question"`)
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Answer.member"`)
	}
	return nil
}

func (_u *AnswerUpdateOne) sqlSave(ctx context.Context) (_node *Answer, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(answer.Table, answer.Columns, sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Answer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, answer.FieldID)
		for _, f := range fields {
			if !answer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != answer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AnswerValue(); ok {
		_spec.SetField(answer.FieldAnswerValue, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(answer.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(answer.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.QuestionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.QuestionTable,
			Columns: []string{answer.QuestionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.MemberTable,
			Columns: []string{answer.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   answer.MemberTable,
			Columns: []string{answer.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Answer{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
