// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"radgifa/ent/member"
	"radgifa/ent/questionnaire"
	"radgifa/ent/user"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Member is the model entity for the Member schema.
type Member struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// Something that only the member knows so they can prove who they are
	UniqueIdentifier string `json:"unique_identifier,omitempty"`
	// It is generated as a string the clear text is send to the member only once, then only the hash is stored. Is not requiered if the member is related to a user.
	PassCode []byte `json:"pass_code,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemberQuery when eager-loading is set.
	Edges                 MemberEdges `json:"edges"`
	questionnaire_members *uuid.UUID
	user_memberships      *uuid.UUID
	selectValues          sql.SelectValues
}

// MemberEdges holds the relations/edges for other nodes in the graph.
type MemberEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Questionnaire holds the value of the questionnaire edge.
	Questionnaire *Questionnaire `json:"questionnaire,omitempty"`
	// Answers holds the value of the answers edge.
	Answers []*Answer `json:"answers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// QuestionnaireOrErr returns the Questionnaire value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemberEdges) QuestionnaireOrErr() (*Questionnaire, error) {
	if e.Questionnaire != nil {
		return e.Questionnaire, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: questionnaire.Label}
	}
	return nil, &NotLoadedError{edge: "questionnaire"}
}

// AnswersOrErr returns the Answers value or an error if the edge
// was not loaded in eager-loading.
func (e MemberEdges) AnswersOrErr() ([]*Answer, error) {
	if e.loadedTypes[2] {
		return e.Answers, nil
	}
	return nil, &NotLoadedError{edge: "answers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Member) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case member.FieldPassCode:
			values[i] = new([]byte)
		case member.FieldCreatedAt:
			values[i] = new(sql.NullInt64)
		case member.FieldDisplayName, member.FieldUniqueIdentifier:
			values[i] = new(sql.NullString)
		case member.FieldID:
			values[i] = new(uuid.UUID)
		case member.ForeignKeys[0]: // questionnaire_members
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case member.ForeignKeys[1]: // user_memberships
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Member fields.
func (_m *Member) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case member.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case member.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case member.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case member.FieldUniqueIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unique_identifier", values[i])
			} else if value.Valid {
				_m.UniqueIdentifier = value.String
			}
		case member.FieldPassCode:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field pass_code", values[i])
			} else if value != nil {
				_m.PassCode = *value
			}
		case member.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field questionnaire_members", values[i])
			} else if value.Valid {
				_m.questionnaire_members = new(uuid.UUID)
				*_m.questionnaire_members = *value.S.(*uuid.UUID)
			}
		case member.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_memberships", values[i])
			} else if value.Valid {
				_m.user_memberships = new(uuid.UUID)
				*_m.user_memberships = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Member.
// This includes values selected through modifiers, order, etc.
func (_m *Member) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Member entity.
func (_m *Member) QueryUser() *UserQuery {
	return NewMemberClient(_m.config).QueryUser(_m)
}

// QueryQuestionnaire queries the "questionnaire" edge of the Member entity.
func (_m *Member) QueryQuestionnaire() *QuestionnaireQuery {
	return NewMemberClient(_m.config).QueryQuestionnaire(_m)
}

// QueryAnswers queries the "answers" edge of the Member entity.
func (_m *Member) QueryAnswers() *AnswerQuery {
	return NewMemberClient(_m.config).QueryAnswers(_m)
}

// Update returns a builder for updating this Member.
// Note that you need to call Member.Unwrap() before calling this method if this Member
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Member) Update() *MemberUpdateOne {
	return NewMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Member entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Member) Unwrap() *Member {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Member is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Member) String() string {
	var builder strings.Builder
	builder.WriteString("Member(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("unique_identifier=")
	builder.WriteString(_m.UniqueIdentifier)
	builder.WriteString(", ")
	builder.WriteString("pass_code=")
	builder.WriteString(fmt.Sprintf("%v", _m.PassCode))
	builder.WriteByte(')')
	return builder.String()
}

// Members is a parsable slice of Member.
type Members []*Member
