// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"radgifa/ent/answer"
	"radgifa/ent/member"
	"radgifa/ent/predicate"
	"radgifa/ent/questionnaire"
	"radgifa/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MemberUpdate is the builder for updating Member entities.
type MemberUpdate struct {
	config
	hooks    []Hook
	mutation *MemberMutation
}

// Where appends a list predicates to the MemberUpdate builder.
func (_u *MemberUpdate) Where(ps ...predicate.Member) *MemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *MemberUpdate) SetDisplayName(v string) *MemberUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableDisplayName(v *string) *MemberUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetUniqueIdentifier sets the "unique_identifier" field.
func (_u *MemberUpdate) SetUniqueIdentifier(v string) *MemberUpdate {
	_u.mutation.SetUniqueIdentifier(v)
	return _u
}

// SetNillableUniqueIdentifier sets the "unique_identifier" field if the given value is not nil.
func (_u *MemberUpdate) SetNillableUniqueIdentifier(v *string) *MemberUpdate {
	if v != nil {
		_u.SetUniqueIdentifier(*v)
	}
	return _u
}

// SetPassCode sets the "pass_code" field.
func (_u *MemberUpdate) SetPassCode(v []byte) *MemberUpdate {
	_u.mutation.SetPassCode(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *MemberUpdate) SetUserID(id uuid.UUID) *MemberUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *MemberUpdate) SetNillableUserID(id *uuid.UUID) *MemberUpdate {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MemberUpdate) SetUser(v *User) *MemberUpdate {
	return _u.SetUserID(v.ID)
}

// SetQuestionnaireID sets the "questionnaire" edge to the Questionnaire entity by ID.
func (_u *MemberUpdate) SetQuestionnaireID(id uuid.UUID) *MemberUpdate {
	_u.mutation.SetQuestionnaireID(id)
	return _u
}

// SetQuestionnaire sets the "questionnaire" edge to the Questionnaire entity.
func (_u *MemberUpdate) SetQuestionnaire(v *Questionnaire) *MemberUpdate {
	return _u.SetQuestionnaireID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the Answer entity by IDs.
func (_u *MemberUpdate) AddAnswerIDs(ids ...uuid.UUID) *MemberUpdate {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answer entity.
func (_u *MemberUpdate) AddAnswers(v ...*Answer) *MemberUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (_u *MemberUpdate) Mutation() *MemberMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MemberUpdate) ClearUser() *MemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearQuestionnaire clears the "questionnaire" edge to the Questionnaire entity.
func (_u *MemberUpdate) ClearQuestionnaire() *MemberUpdate {
	_u.mutation.ClearQuestionnaire()
	return _u
}

// ClearAnswers clears all "answers" edges to the Answer entity.
func (_u *MemberUpdate) ClearAnswers() *MemberUpdate {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answer entities by IDs.
func (_u *MemberUpdate) RemoveAnswerIDs(ids ...uuid.UUID) *MemberUpdate {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answer entities.
func (_u *MemberUpdate) RemoveAnswers(v ...*Answer) *MemberUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberUpdate) check() error {
	if _u.mutation.QuestionnaireCleared() && len(_u.mutation.QuestionnaireIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Member.questionnaire"`)
	}
	return nil
}

func (_u *MemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(member.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UniqueIdentifier(); ok {
		_spec.SetField(member.FieldUniqueIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassCode(); ok {
		_spec.SetField(member.FieldPassCode, field.TypeBytes, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.UserTable,
			Columns: []string{member.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.UserTable,
			Columns: []string{member.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionnaireCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.QuestionnaireTable,
			Columns: []string{member.QuestionnaireColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questionnaire.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionnaireIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.QuestionnaireTable,
			Columns: []string{member.QuestionnaireColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questionnaire.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.AnswersTable,
			Columns: []string{member.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.AnswersTable,
			Columns: []string{member.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.AnswersTable,
			Columns: []string{member.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberUpdateOne is the builder for updating a single Member entity.
type MemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberMutation
}

// SetDisplayName sets the "display_name" field.
func (_u *MemberUpdateOne) SetDisplayName(v string) *MemberUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableDisplayName(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetUniqueIdentifier sets the "unique_identifier" field.
func (_u *MemberUpdateOne) SetUniqueIdentifier(v string) *MemberUpdateOne {
	_u.mutation.SetUniqueIdentifier(v)
	return _u
}

// SetNillableUniqueIdentifier sets the "unique_identifier" field if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableUniqueIdentifier(v *string) *MemberUpdateOne {
	if v != nil {
		_u.SetUniqueIdentifier(*v)
	}
	return _u
}

// SetPassCode sets the "pass_code" field.
func (_u *MemberUpdateOne) SetPassCode(v []byte) *MemberUpdateOne {
	_u.mutation.SetPassCode(v)
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *MemberUpdateOne) SetUserID(id uuid.UUID) *MemberUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_u *MemberUpdateOne) SetNillableUserID(id *uuid.UUID) *MemberUpdateOne {
	if id != nil {
		_u = _u.SetUserID(*id)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *MemberUpdateOne) SetUser(v *User) *MemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetQuestionnaireID sets the "questionnaire" edge to the Questionnaire entity by ID.
func (_u *MemberUpdateOne) SetQuestionnaireID(id uuid.UUID) *MemberUpdateOne {
	_u.mutation.SetQuestionnaireID(id)
	return _u
}

// SetQuestionnaire sets the "questionnaire" edge to the Questionnaire entity.
func (_u *MemberUpdateOne) SetQuestionnaire(v *Questionnaire) *MemberUpdateOne {
	return _u.SetQuestionnaireID(v.ID)
}

// AddAnswerIDs adds the "answers" edge to the Answer entity by IDs.
func (_u *MemberUpdateOne) AddAnswerIDs(ids ...uuid.UUID) *MemberUpdateOne {
	_u.mutation.AddAnswerIDs(ids...)
	return _u
}

// AddAnswers adds the "answers" edges to the Answer entity.
func (_u *MemberUpdateOne) AddAnswers(v ...*Answer) *MemberUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnswerIDs(ids...)
}

// Mutation returns the MemberMutation object of the builder.
func (_u *MemberUpdateOne) Mutation() *MemberMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *MemberUpdateOne) ClearUser() *MemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearQuestionnaire clears the "questionnaire" edge to the Questionnaire entity.
func (_u *MemberUpdateOne) ClearQuestionnaire() *MemberUpdateOne {
	_u.mutation.ClearQuestionnaire()
	return _u
}

// ClearAnswers clears all "answers" edges to the Answer entity.
func (_u *MemberUpdateOne) ClearAnswers() *MemberUpdateOne {
	_u.mutation.ClearAnswers()
	return _u
}

// RemoveAnswerIDs removes the "answers" edge to Answer entities by IDs.
func (_u *MemberUpdateOne) RemoveAnswerIDs(ids ...uuid.UUID) *MemberUpdateOne {
	_u.mutation.RemoveAnswerIDs(ids...)
	return _u
}

// RemoveAnswers removes "answers" edges to Answer entities.
func (_u *MemberUpdateOne) RemoveAnswers(v ...*Answer) *MemberUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnswerIDs(ids...)
}

// Where appends a list predicates to the MemberUpdate builder.
func (_u *MemberUpdateOne) Where(ps ...predicate.Member) *MemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberUpdateOne) Select(field string, fields ...string) *MemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Member entity.
func (_u *MemberUpdateOne) Save(ctx context.Context) (*Member, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberUpdateOne) SaveX(ctx context.Context) *Member {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberUpdateOne) check() error {
	if _u.mutation.QuestionnaireCleared() && len(_u.mutation.QuestionnaireIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Member.questionnaire"`)
	}
	return nil
}

func (_u *MemberUpdateOne) sqlSave(ctx context.Context) (_node *Member, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(member.Table, member.Columns, sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Member.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, member.FieldID)
		for _, f := range fields {
			if !member.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != member.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(member.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UniqueIdentifier(); ok {
		_spec.SetField(member.FieldUniqueIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.PassCode(); ok {
		_spec.SetField(member.FieldPassCode, field.TypeBytes, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.UserTable,
			Columns: []string{member.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.UserTable,
			Columns: []string{member.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestionnaireCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.QuestionnaireTable,
			Columns: []string{member.QuestionnaireColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questionnaire.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestionnaireIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.QuestionnaireTable,
			Columns: []string{member.QuestionnaireColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(questionnaire.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.AnswersTable,
			Columns: []string{member.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnswersIDs(); len(nodes) > 0 && !_u.mutation.AnswersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.AnswersTable,
			Columns: []string{member.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnswersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   member.AnswersTable,
			Columns: []string{member.AnswersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(answer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Member{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{member.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
