// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"radgifa/ent/member"
	"radgifa/ent/predicate"
	"radgifa/ent/question"
	"radgifa/ent/questionnaire"
	"radgifa/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// QuestionnaireQuery is the builder for querying Questionnaire entities.
type QuestionnaireQuery struct {
	config
	ctx           *QueryContext
	order         []questionnaire.OrderOption
	inters        []Interceptor
	predicates    []predicate.Questionnaire
	withOwner     *UserQuery
	withMembers   *MemberQuery
	withQuestions *QuestionQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuestionnaireQuery builder.
func (_q *QuestionnaireQuery) Where(ps ...predicate.Questionnaire) *QuestionnaireQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *QuestionnaireQuery) Limit(limit int) *QuestionnaireQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *QuestionnaireQuery) Offset(offset int) *QuestionnaireQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *QuestionnaireQuery) Unique(unique bool) *QuestionnaireQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *QuestionnaireQuery) Order(o ...questionnaire.OrderOption) *QuestionnaireQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOwner chains the current query on the "owner" edge.
func (_q *QuestionnaireQuery) QueryOwner() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(questionnaire.Table, questionnaire.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, questionnaire.OwnerTable, questionnaire.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMembers chains the current query on the "members" edge.
func (_q *QuestionnaireQuery) QueryMembers() *MemberQuery {
	query := (&MemberClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(questionnaire.Table, questionnaire.FieldID, selector),
			sqlgraph.To(member.Table, member.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, questionnaire.MembersTable, questionnaire.MembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryQuestions chains the current query on the "questions" edge.
func (_q *QuestionnaireQuery) QueryQuestions() *QuestionQuery {
	query := (&QuestionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(questionnaire.Table, questionnaire.FieldID, selector),
			sqlgraph.To(question.Table, question.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, questionnaire.QuestionsTable, questionnaire.QuestionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Questionnaire entity from the query.
// Returns a *NotFoundError when no Questionnaire was found.
func (_q *QuestionnaireQuery) First(ctx context.Context) (*Questionnaire, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{questionnaire.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *QuestionnaireQuery) FirstX(ctx context.Context) *Questionnaire {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Questionnaire ID from the query.
// Returns a *NotFoundError when no Questionnaire ID was found.
func (_q *QuestionnaireQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{questionnaire.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *QuestionnaireQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Questionnaire entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Questionnaire entity is found.
// Returns a *NotFoundError when no Questionnaire entities are found.
func (_q *QuestionnaireQuery) Only(ctx context.Context) (*Questionnaire, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{questionnaire.Label}
	default:
		return nil, &NotSingularError{questionnaire.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *QuestionnaireQuery) OnlyX(ctx context.Context) *Questionnaire {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Questionnaire ID in the query.
// Returns a *NotSingularError when more than one Questionnaire ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *QuestionnaireQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{questionnaire.Label}
	default:
		err = &NotSingularError{questionnaire.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *QuestionnaireQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Questionnaires.
func (_q *QuestionnaireQuery) All(ctx context.Context) ([]*Questionnaire, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Questionnaire, *QuestionnaireQuery]()
	return withInterceptors[[]*Questionnaire](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *QuestionnaireQuery) AllX(ctx context.Context) []*Questionnaire {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Questionnaire IDs.
func (_q *QuestionnaireQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(questionnaire.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *QuestionnaireQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *QuestionnaireQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*QuestionnaireQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *QuestionnaireQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *QuestionnaireQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *QuestionnaireQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuestionnaireQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *QuestionnaireQuery) Clone() *QuestionnaireQuery {
	if _q == nil {
		return nil
	}
	return &QuestionnaireQuery{
		config:        _q.config,
		ctx:           _q.ctx.Clone(),
		order:         append([]questionnaire.OrderOption{}, _q.order...),
		inters:        append([]Interceptor{}, _q.inters...),
		predicates:    append([]predicate.Questionnaire{}, _q.predicates...),
		withOwner:     _q.withOwner.Clone(),
		withMembers:   _q.withMembers.Clone(),
		withQuestions: _q.withQuestions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuestionnaireQuery) WithOwner(opts ...func(*UserQuery)) *QuestionnaireQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOwner = query
	return _q
}

// WithMembers tells the query-builder to eager-load the nodes that are connected to
// the "members" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuestionnaireQuery) WithMembers(opts ...func(*MemberQuery)) *QuestionnaireQuery {
	query := (&MemberClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMembers = query
	return _q
}

// WithQuestions tells the query-builder to eager-load the nodes that are connected to
// the "questions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *QuestionnaireQuery) WithQuestions(opts ...func(*QuestionQuery)) *QuestionnaireQuery {
	query := (&QuestionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withQuestions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Questionnaire.Query().
//		GroupBy(questionnaire.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *QuestionnaireQuery) GroupBy(field string, fields ...string) *QuestionnaireGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuestionnaireGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = questionnaire.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.Questionnaire.Query().
//		Select(questionnaire.FieldTitle).
//		Scan(ctx, &v)
func (_q *QuestionnaireQuery) Select(fields ...string) *QuestionnaireSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &QuestionnaireSelect{QuestionnaireQuery: _q}
	sbuild.label = questionnaire.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuestionnaireSelect configured with the given aggregations.
func (_q *QuestionnaireQuery) Aggregate(fns ...AggregateFunc) *QuestionnaireSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *QuestionnaireQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !questionnaire.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *QuestionnaireQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Questionnaire, error) {
	var (
		nodes       = []*Questionnaire{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withOwner != nil,
			_q.withMembers != nil,
			_q.withQuestions != nil,
		}
	)
	if _q.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, questionnaire.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Questionnaire).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Questionnaire{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOwner; query != nil {
		if err := _q.loadOwner(ctx, query, nodes, nil,
			func(n *Questionnaire, e *User) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMembers; query != nil {
		if err := _q.loadMembers(ctx, query, nodes,
			func(n *Questionnaire) { n.Edges.Members = []*Member{} },
			func(n *Questionnaire, e *Member) { n.Edges.Members = append(n.Edges.Members, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withQuestions; query != nil {
		if err := _q.loadQuestions(ctx, query, nodes,
			func(n *Questionnaire) { n.Edges.Questions = []*Question{} },
			func(n *Questionnaire, e *Question) { n.Edges.Questions = append(n.Edges.Questions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *QuestionnaireQuery) loadOwner(ctx context.Context, query *UserQuery, nodes []*Questionnaire, init func(*Questionnaire), assign func(*Questionnaire, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Questionnaire)
	for i := range nodes {
		if nodes[i].user_questionnaires == nil {
			continue
		}
		fk := *nodes[i].user_questionnaires
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_questionnaires" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *QuestionnaireQuery) loadMembers(ctx context.Context, query *MemberQuery, nodes []*Questionnaire, init func(*Questionnaire), assign func(*Questionnaire, *Member)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Questionnaire)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Member(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(questionnaire.MembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.questionnaire_members
		if fk == nil {
			return fmt.Errorf(`foreign-key "questionnaire_members" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "questionnaire_members" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *QuestionnaireQuery) loadQuestions(ctx context.Context, query *QuestionQuery, nodes []*Questionnaire, init func(*Questionnaire), assign func(*Questionnaire, *Question)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Questionnaire)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Question(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(questionnaire.QuestionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.questionnaire_questions
		if fk == nil {
			return fmt.Errorf(`foreign-key "questionnaire_questions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "questionnaire_questions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *QuestionnaireQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *QuestionnaireQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(questionnaire.Table, questionnaire.Columns, sqlgraph.NewFieldSpec(questionnaire.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, questionnaire.FieldID)
		for i := range fields {
			if fields[i] != questionnaire.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *QuestionnaireQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(questionnaire.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = questionnaire.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// QuestionnaireGroupBy is the group-by builder for Questionnaire entities.
type QuestionnaireGroupBy struct {
	selector
	build *QuestionnaireQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *QuestionnaireGroupBy) Aggregate(fns ...AggregateFunc) *QuestionnaireGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *QuestionnaireGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuestionnaireQuery, *QuestionnaireGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *QuestionnaireGroupBy) sqlScan(ctx context.Context, root *QuestionnaireQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuestionnaireSelect is the builder for selecting fields of Questionnaire entities.
type QuestionnaireSelect struct {
	*QuestionnaireQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *QuestionnaireSelect) Aggregate(fns ...AggregateFunc) *QuestionnaireSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *QuestionnaireSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuestionnaireQuery, *QuestionnaireSelect](ctx, _s.QuestionnaireQuery, _s, _s.inters, v)
}

func (_s *QuestionnaireSelect) sqlScan(ctx context.Context, root *QuestionnaireQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
