// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"radgifa/ent/member"
	"radgifa/ent/question"
	"radgifa/ent/questionnaire"
	"radgifa/ent/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// QuestionnaireCreate is the builder for creating a Questionnaire entity.
type QuestionnaireCreate struct {
	config
	mutation *QuestionnaireMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *QuestionnaireCreate) SetTitle(v string) *QuestionnaireCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *QuestionnaireCreate) SetDescription(v string) *QuestionnaireCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *QuestionnaireCreate) SetNillableDescription(v *string) *QuestionnaireCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsPublished sets the "is_published" field.
func (_c *QuestionnaireCreate) SetIsPublished(v bool) *QuestionnaireCreate {
	_c.mutation.SetIsPublished(v)
	return _c
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_c *QuestionnaireCreate) SetNillableIsPublished(v *bool) *QuestionnaireCreate {
	if v != nil {
		_c.SetIsPublished(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuestionnaireCreate) SetCreatedAt(v int64) *QuestionnaireCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuestionnaireCreate) SetNillableCreatedAt(v *int64) *QuestionnaireCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuestionnaireCreate) SetID(v uuid.UUID) *QuestionnaireCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *QuestionnaireCreate) SetOwnerID(id uuid.UUID) *QuestionnaireCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *QuestionnaireCreate) SetOwner(v *User) *QuestionnaireCreate {
	return _c.SetOwnerID(v.ID)
}

// AddMemberIDs adds the "members" edge to the Member entity by IDs.
func (_c *QuestionnaireCreate) AddMemberIDs(ids ...uuid.UUID) *QuestionnaireCreate {
	_c.mutation.AddMemberIDs(ids...)
	return _c
}

// AddMembers adds the "members" edges to the Member entity.
func (_c *QuestionnaireCreate) AddMembers(v ...*Member) *QuestionnaireCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberIDs(ids...)
}

// AddQuestionIDs adds the "questions" edge to the Question entity by IDs.
func (_c *QuestionnaireCreate) AddQuestionIDs(ids ...uuid.UUID) *QuestionnaireCreate {
	_c.mutation.AddQuestionIDs(ids...)
	return _c
}

// AddQuestions adds the "questions" edges to the Question entity.
func (_c *QuestionnaireCreate) AddQuestions(v ...*Question) *QuestionnaireCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddQuestionIDs(ids...)
}

// Mutation returns the QuestionnaireMutation object of the builder.
func (_c *QuestionnaireCreate) Mutation() *QuestionnaireMutation {
	return _c.mutation
}

// Save creates the Questionnaire in the database.
func (_c *QuestionnaireCreate) Save(ctx context.Context) (*Questionnaire, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuestionnaireCreate) SaveX(ctx context.Context) *Questionnaire {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestionnaireCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestionnaireCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuestionnaireCreate) defaults() {
	if _, ok := _c.mutation.IsPublished(); !ok {
		v := questionnaire.DefaultIsPublished
		_c.mutation.SetIsPublished(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := questionnaire.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuestionnaireCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Questionnaire.title"`)}
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		return &ValidationError{Name: "is_published", err: errors.New(`ent: missing required field "Questionnaire.is_published"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Questionnaire.created_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Questionnaire.owner"`)}
	}
	return nil
}

func (_c *QuestionnaireCreate) sqlSave(ctx context.Context) (*Questionnaire, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuestionnaireCreate) createSpec() (*Questionnaire, *sqlgraph.CreateSpec) {
	var (
		_node = &Questionnaire{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(questionnaire.Table, sqlgraph.NewFieldSpec(questionnaire.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(questionnaire.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(questionnaire.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsPublished(); ok {
		_spec.SetField(questionnaire.FieldIsPublished, field.TypeBool, value)
		_node.IsPublished = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(questionnaire.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   questionnaire.OwnerTable,
			Columns: []string{questionnaire.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_questionnaires = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questionnaire.MembersTable,
			Columns: []string{questionnaire.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(member.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.QuestionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   questionnaire.QuestionsTable,
			Columns: []string{questionnaire.QuestionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(question.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// QuestionnaireCreateBulk is the builder for creating many Questionnaire entities in bulk.
type QuestionnaireCreateBulk struct {
	config
	err      error
	builders []*QuestionnaireCreate
}

// Save creates the Questionnaire entities in the database.
func (_c *QuestionnaireCreateBulk) Save(ctx context.Context) ([]*Questionnaire, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Questionnaire, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestionnaireMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuestionnaireCreateBulk) SaveX(ctx context.Context) []*Questionnaire {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestionnaireCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestionnaireCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
