// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"radgifa/ent/questionnaire"
	"radgifa/ent/user"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Questionnaire is the model entity for the Questionnaire schema.
type Questionnaire struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// IsPublished holds the value of the "is_published" field.
	IsPublished bool `json:"is_published,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QuestionnaireQuery when eager-loading is set.
	Edges               QuestionnaireEdges `json:"edges"`
	user_questionnaires *uuid.UUID
	selectValues        sql.SelectValues
}

// QuestionnaireEdges holds the relations/edges for other nodes in the graph.
type QuestionnaireEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Members holds the value of the members edge.
	Members []*Member `json:"members,omitempty"`
	// Questions holds the value of the questions edge.
	Questions []*Question `json:"questions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e QuestionnaireEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e QuestionnaireEdges) MembersOrErr() ([]*Member, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// QuestionsOrErr returns the Questions value or an error if the edge
// was not loaded in eager-loading.
func (e QuestionnaireEdges) QuestionsOrErr() ([]*Question, error) {
	if e.loadedTypes[2] {
		return e.Questions, nil
	}
	return nil, &NotLoadedError{edge: "questions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Questionnaire) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case questionnaire.FieldIsPublished:
			values[i] = new(sql.NullBool)
		case questionnaire.FieldCreatedAt:
			values[i] = new(sql.NullInt64)
		case questionnaire.FieldTitle, questionnaire.FieldDescription:
			values[i] = new(sql.NullString)
		case questionnaire.FieldID:
			values[i] = new(uuid.UUID)
		case questionnaire.ForeignKeys[0]: // user_questionnaires
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Questionnaire fields.
func (_m *Questionnaire) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case questionnaire.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case questionnaire.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case questionnaire.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case questionnaire.FieldIsPublished:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_published", values[i])
			} else if value.Valid {
				_m.IsPublished = value.Bool
			}
		case questionnaire.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case questionnaire.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_questionnaires", values[i])
			} else if value.Valid {
				_m.user_questionnaires = new(uuid.UUID)
				*_m.user_questionnaires = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Questionnaire.
// This includes values selected through modifiers, order, etc.
func (_m *Questionnaire) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Questionnaire entity.
func (_m *Questionnaire) QueryOwner() *UserQuery {
	return NewQuestionnaireClient(_m.config).QueryOwner(_m)
}

// QueryMembers queries the "members" edge of the Questionnaire entity.
func (_m *Questionnaire) QueryMembers() *MemberQuery {
	return NewQuestionnaireClient(_m.config).QueryMembers(_m)
}

// QueryQuestions queries the "questions" edge of the Questionnaire entity.
func (_m *Questionnaire) QueryQuestions() *QuestionQuery {
	return NewQuestionnaireClient(_m.config).QueryQuestions(_m)
}

// Update returns a builder for updating this Questionnaire.
// Note that you need to call Questionnaire.Unwrap() before calling this method if this Questionnaire
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Questionnaire) Update() *QuestionnaireUpdateOne {
	return NewQuestionnaireClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Questionnaire entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Questionnaire) Unwrap() *Questionnaire {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Questionnaire is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Questionnaire) String() string {
	var builder strings.Builder
	builder.WriteString("Questionnaire(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("is_published=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPublished))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteByte(')')
	return builder.String()
}

// Questionnaires is a parsable slice of Questionnaire.
type Questionnaires []*Questionnaire
