// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"radgifa/ent/predicate"
	"radgifa/ent/questionnaire"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestionnaireDelete is the builder for deleting a Questionnaire entity.
type QuestionnaireDelete struct {
	config
	hooks    []Hook
	mutation *QuestionnaireMutation
}

// Where appends a list predicates to the QuestionnaireDelete builder.
func (_d *QuestionnaireDelete) Where(ps ...predicate.Questionnaire) *QuestionnaireDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *QuestionnaireDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuestionnaireDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *QuestionnaireDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(questionnaire.Table, sqlgraph.NewFieldSpec(questionnaire.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// QuestionnaireDeleteOne is the builder for deleting a single Questionnaire entity.
type QuestionnaireDeleteOne struct {
	_d *QuestionnaireDelete
}

// Where appends a list predicates to the QuestionnaireDelete builder.
func (_d *QuestionnaireDeleteOne) Where(ps ...predicate.Questionnaire) *QuestionnaireDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *QuestionnaireDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{questionnaire.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *QuestionnaireDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
