// Code generated by ent, DO NOT EDIT.

package ent

import (
	"radgifa/ent/answer"
	"radgifa/ent/member"
	"radgifa/ent/question"
	"radgifa/ent/questionnaire"
	"radgifa/ent/schema"
	"radgifa/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	answerFields := schema.Answer{}.Fields()
	_ = answerFields
	// answerDescCreatedAt is the schema descriptor for created_at field.
	answerDescCreatedAt := answerFields[2].Descriptor()
	// answer.DefaultCreatedAt holds the default value on creation for the created_at field.
	answer.DefaultCreatedAt = answerDescCreatedAt.Default.(func() int64)
	// answerDescUpdatedAt is the schema descriptor for updated_at field.
	answerDescUpdatedAt := answerFields[3].Descriptor()
	// answer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	answer.DefaultUpdatedAt = answerDescUpdatedAt.Default.(func() int64)
	// answerDescID is the schema descriptor for id field.
	answerDescID := answerFields[0].Descriptor()
	// answer.DefaultID holds the default value on creation for the id field.
	answer.DefaultID = answerDescID.Default.(func() uuid.UUID)
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescCreatedAt is the schema descriptor for created_at field.
	memberDescCreatedAt := memberFields[2].Descriptor()
	// member.DefaultCreatedAt holds the default value on creation for the created_at field.
	member.DefaultCreatedAt = memberDescCreatedAt.Default.(func() int64)
	// memberDescID is the schema descriptor for id field.
	memberDescID := memberFields[0].Descriptor()
	// member.DefaultID holds the default value on creation for the id field.
	member.DefaultID = memberDescID.Default.(func() uuid.UUID)
	questionFields := schema.Question{}.Fields()
	_ = questionFields
	// questionDescTheme is the schema descriptor for theme field.
	questionDescTheme := questionFields[1].Descriptor()
	// question.ThemeValidator is a validator for the "theme" field. It is called by the builders before save.
	question.ThemeValidator = questionDescTheme.Validators[0].(func(string) error)
	// questionDescCreatedAt is the schema descriptor for created_at field.
	questionDescCreatedAt := questionFields[2].Descriptor()
	// question.DefaultCreatedAt holds the default value on creation for the created_at field.
	question.DefaultCreatedAt = questionDescCreatedAt.Default.(func() int64)
	// questionDescID is the schema descriptor for id field.
	questionDescID := questionFields[0].Descriptor()
	// question.DefaultID holds the default value on creation for the id field.
	question.DefaultID = questionDescID.Default.(func() uuid.UUID)
	questionnaireFields := schema.Questionnaire{}.Fields()
	_ = questionnaireFields
	// questionnaireDescIsPublished is the schema descriptor for is_published field.
	questionnaireDescIsPublished := questionnaireFields[3].Descriptor()
	// questionnaire.DefaultIsPublished holds the default value on creation for the is_published field.
	questionnaire.DefaultIsPublished = questionnaireDescIsPublished.Default.(bool)
	// questionnaireDescCreatedAt is the schema descriptor for created_at field.
	questionnaireDescCreatedAt := questionnaireFields[4].Descriptor()
	// questionnaire.DefaultCreatedAt holds the default value on creation for the created_at field.
	questionnaire.DefaultCreatedAt = questionnaireDescCreatedAt.Default.(func() int64)
	// questionnaireDescID is the schema descriptor for id field.
	questionnaireDescID := questionnaireFields[0].Descriptor()
	// questionnaire.DefaultID holds the default value on creation for the id field.
	questionnaire.DefaultID = questionnaireDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() int64)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
